version: "3"
services:
  apache:
    image: 'apache'
    build: 
       context: .
       dockerfile: ./Dockerfile
    ports:
        - '80:80'
  webchecker:
    image: 'checker'
    build: 
       context: .
       dockerfile: ./checker.Dockerfile
    ports:
       - 3000:3000
    volumes:
      - ./output:/output
  jenkins:
    image: "jenkins/jenkins:lts"
    privileged: true
    user: "root"
    ports:
      - "0000:0000"
      - "5000:5000"
    dns:
      - 8.8.8.8
    volumes:
      - "./jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/usr/bin/docker:/usr/bin/docker"