version: "3"
services:
  apache:
    image: 'apache'
    build: 
       context: .
       dockerfile: ./Dockerfile
    ports:
        - '80:80'
  webchecker:
    image: 'checker'
    build: 
       context: .
       dockerfile: ./checker.Dockerfile
    ports:
       - 3000:3000
    volumes:
      - ./output:/output